sudo: required
dist: trusty
language: python
python:
  - "2.7"
services:
  - docker
addons:
  apt:
    packages:
      - openvswitch-switch
env:
  - DOCKER_STARTUP_TIMEOUT_MS=60000
install:
  - bin/setup_install
  - bin/setup_build
script:
  - bin/test_daq
