sudo: required
dist: trusty
language: python
python:
  - "2.7"
services:
  - docker
addons:
  apt:
    packages:
      - openvswitch-switch
install:
  - bin/setup_install
  - bin/setup_core
  - bin/setup_build
script:
  - bin/test_daq
env:
  matrix:
    - FOO=bar
    - MODE=in BUILD=in PUSH=daqf/runner
    - MODE=in BUILD=no
    - DEVICES=3
    - SWITCH=ext
deploy:
  provider: script
  script: bash bin/docker_push
  on:
    branch: release
