sudo: required
dist: trusty
language: python
python:
  - "2.7"
services:
  - docker
addons:
  apt:
    packages:
      - openvswitch-switch
install:
  - bin/setup_install
  - /etc/init.d/openvswitch-controller stop
script:
  - bin/run_travis_test
