sudo: required
dist: trusty
language: python
python:
  - "2.7"
services:
  - docker
addons:
  apt:
    packages:
      - openvswitch-switch
install:
  - bin/setup_install
  - bin/setup_build
script:
  - bin/test_daq
env:
  matrix:
    - MULTI=n MODE=in
    - MULTI=n MODE=ex
    - MULTI=y MODE=ex
