sudo: required
dist: trusty
language: python
python:
  - "2.7"
services:
  - docker
addons:
  apt:
    update: true
    packages:
      - openvswitch-switch
install:
  - bin/setup_install
  - bin/setup_core
  - bin/setup_build
script:
  - bin/test_daq
env:
  matrix:
    - DAQ_MODE=
    - DAQ_MODE=in DAQ_BUILD=in DAQ_PUSH=daqf/runner
    - DAQ_MODE=in DAQ_BUILD=no
    - DAQ_DEVICES=1 DAQ_FAIL=xdhcp
    - DAQ_DEVICES=3
    - DAQ_SWITCH=ext
branches:
  except:
  - /^release-\d+\.\d+(\.\d+)?$/
deploy:
  provider: script
  script: bash bin/docker_push
  on:
    branch: release
