sudo: required
dist: trusty
language: python
python:
  - "2.7"
services:
  - docker
addons:
  apt:
    packages:
      - openvswitch-switch
before_install:
  - echo 'DOCKER_OPTS="-s overlay2"' | sudo tee /etc/default/docker
  - sudo service docker restart
install:
  - bin/setup_install
script:
  - bin/run_travis_test
