#!/bin/bash -e

# Setup

source reporting.sh

REPORT=/tmp/report.txt
LOCAL_REPORT=/tmp/local.report.txt
CONFIG=/config/device/module_config.json
MANIFEST=./module_manifest.json

# Test definition

REDACTED_LOG=/tmp/script.kiddie.report.log

# Execute the test binaries

echo Running spurious DDoS script... | tee -a $REDACTED_LOG

python3 ddos.py -p 80 -a $TARGET_IP | tee -a $REDACTED_LOG

echo Running test that does nothing... | tee -a $REDACTED_LOG

# Write results to the .md report

RESULT_AND_SUMMARY="$(grep "RESULT" $LOCAL_REPORT)"
grep -v "RESULT" $LOCAL_REPORT >> $REDACTED_LOG

echo Writing...

write_out_result $REPORT \
                 "needless.script.kiddie" \
                 "$(jq -r '.["needless.script.kiddie"].desc' $MANIFEST)" \
                 "This test ran fine" \
                 "$RESULT_AND_SUMMARY"

echo Writing done...

# [ $(check_for_fails_in "${result_lines[@]}") == false ]

