#!/bin/bash -e

# Setup

source reporting.sh

REPORT=/tmp/report.txt
LOCAL_REPORT=report/report.txt
CONFIG=/config/device/module_config.json
LOG=/tmp/nmap.log
RESULT_LINES=/tmp/result_lines.txt

# Test definition

TEST_NAME="connection.mac_oui"
TEST_DESCRIPTION="Check Physical device address OUI against IEEE registration and verify it is registered with the correct manufacturer"
REDACTED_LOG=/tmp/macoui.report.log

# Execute the test binaries

echo Running spurious DDoS script... | tee -a $REDACTED_LOG

java -jar mac_oui/build/libs/mac_oui-all.jar $TARGET_MAC

echo Running test that does nothing... | tee -a $REDACTED_LOG

# Write results to the .md report

RESULT_AND_SUMMARY="$(grep "RESULT" $LOCAL_REPORT)"
grep -v "RESULT" $LOCAL_REPORT >> $REDACTED_LOG

write_out_result $REPORT \
                 "$TEST_NAME" \
                 "$TEST_DESCRIPTION" \
                 "$(cat $REDACTED_LOG)" \
                 "$RESULT_AND_SUMMARY"

result_lines=( "$RESULT_AND_SUMMARY" )

[ $(check_for_fails_in "${result_lines[@]}") == false ]

