#!/bin/bash -e

# Setup

source reporting.sh

REPORT=/tmp/report.txt
LOCAL_REPORT=/tmp/local.report.txt
CONFIG=/config/device/module_config.json
MANIFEST=./module_manifest.json
RESULT_LINES=/tmp/result_lines.txt
REDACTED_LOG=/tmp/script.kiddie.report.log

# Execute the test binaries

echo Running spurious DDoS script... | tee -a $REDACTED_LOG

python3 ddos.py -p 80 -a $TARGET_IP | tee -a $REDACTED_LOG

echo Running test that does nothing... | tee -a $REDACTED_LOG

python3 ddos.py -n | tee -a $REDACTED_LOG

# Write out a report monolog

cat $RESULT_LINES

write_out_monolog $REPORT \
                  $MANIFEST \
                  $REDACTED_LOG \
                  $RESULT_LINES

